### PR TITLE
Fix logoLink on redesign

### LINKED ISSUE #4968: LogoLink - redesign compatibility
`document.querySelector('.header a[href="/"]')` should work just fine. May need to be updated occasionally if react thrashes it.

### PR DESCRIPTION
**Pull request by schilkyl**
Fixes #4968 
Tested in browser: firefox

image
Cursor isn't shown in snip but hovering on the logo.

### CODE REVIEW

**Comment by Jarob22** [comment]
This seems a little rude when I was in the original issue checking whether my solution (that you've used) was correct, but you do you, I guess. =/

**Comment by schilkyl** [comment]
I was just getting it done. Sorry if I stepped on your toes.

**Comment by Jarob22** [comment]
I was trying to get started on a small easy pr thats all, and it wasnt really clear what this feature was supposed to do, so I didnt know what to do to test it.

**Comment by schilkyl** [comment]
@Jarob22 do you hvae the module enabled?

**Comment by Jarob22** [comment]
Ah maybe not. How do I do that?

**Comment by schilkyl** [comment]
RES Settings -> Broswing -> Logo Link -> On

image

**Comment by Jarob22** [comment]
Thank you! I’ll take a look tomorrow - am in bed now! Do please carry on here - sorry for being a bit short before, I’ll make it more clear next time I pick up something that I’m either waiting for a response or am in progress.

**Comment by Jarob22** [comment]
@schilkyl That seems to have worked, thank you!

**Comment by larsjohnsen** [comment]
Thanks!

**Pull request merged**
