### PR TITLE
vendor: Update guiders to 2.0.0

### PR DESCRIPTION
**Pull request by mc10**
I don't think anything major has changed, but this deserves another look.

### CODE REVIEW

**Comment by andytuba** [comment]
I haven't dug in too deep yet, but --

I see a lot of class name changes from `guider...` to `guiders...`.  Does it matter to us?

**Comment by mc10** [comment]
Yes, we need to update our CSS as well. I'll look into that.

**Comment by mc10** [comment]
I've updated the CSS, though I didn't add in the `guider_content h2`, `guider_content td`, `.guider_content td + td`, and `.guider_content td code` blocks. Any idea what they were for?

**Comment by andytuba** [comment]
Those .guider_content blocks were for the RES Tips / keyboard nav table that shows up on some tips.  They probably deserve a visual redesign.

**Pull request merged**
