### PR TITLE
Support for properly embedding and crediting staticflickr URLs

### PR DESCRIPTION
**Pull request by alex-seville**
Add support for properly embedding and crediting staticflickr URLs.

Right now when people link directly to the CDN copy of a flickr image (i.e. http://c1.staticflickr.com/9/8345/8186873856_5d36a04f3e_k.jpg) it doesn't pass the detect regexes.

This code allows the photo oembed data to be retrieved by: 
- extracting the photoid embedded within the staticflickr URL
- encoding it to base 58
- rendering it into a Flickr short url for noembed to consume 

This ensures the image is shown and that the credit is preserved.

### CODE REVIEW

**Comment by alex-seville** [comment]
I'll clean up the lint issues, but in the meantime let me know if the change seems good. Thx.

**Comment by alex-seville** [comment]
cc @erikdesjardins

**Comment by erikdesjardins** [comment]
Yes, I'll review this in a few days, we're preparing a release right now

**Comment by erikdesjardins** [comment]
Great, thanks!

**Pull request merged**
