### PR TITLE
Fix handling of image hrefs - images in albums link to the album

### LINKED ISSUE #2605: Clicking image in album doesn't go to album
https://www.reddit.com/r/Enhancement/comments/40hgpo/clicking_an_inline_image_thats_part_of_an_album/

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2605

Should be able to cherry-pick this to 4.6.1 without conflict.

### CODE REVIEW

**Comment by mc10** [comment]
This is close (probably close enough), but the link doesn't point to the specific image in the album, which RES does for any other images when you press prev/next. Do you know where the code is for next/prev links?

**Comment by erikdesjardins** [comment]
That's done explicitly by the individual siteModules ([e.g.](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/ac20a876fa7fd36e8ba21ee7472d3f7b3955cea9/lib/modules/hosts/imgur.js#L255)) - so I don't see why it wouldn't work (`addImage()` is called for each image in the album). I'll check again.

**Comment by gfairchild** [comment]
This has been a bug with Vidble albums for months. Will this PR fix it for Vidble albums as well?

**Comment by erikdesjardins** [comment]
Vidble albums have always [intentionally linked to the image itself](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/1adca0c5585505570706a589110db05038f38dfa/lib/modules/hosts/vidble.js#L62), unrelated to this issue. I could fix that separately, I guess.

**Comment by gfairchild** [comment]
It makes sense to fix that. Basically, all albums should function the same, regardless of host. Clicking on the image to take the user directly to the album anchored on the clicked image is the correct behavior.

**Pull request merged**
