### PR TITLE
Temporarily disable uploader, remove Imgrush

### LINKED ISSUE #2552: Upload.js only has one host and it's been down for some time (imgrush)
Trying to upload an image:

> https://imgrush.com/api/upload/file Failed to load resource: the server responded with a status of 521 (OK)

Should probably 'hide' the module until another host is added.

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2552.

I don't think Imgrush is coming back, so everything is torn out (no activity on Twitter since June, subreddit is private, [no posts using it](https://www.reddit.com/domain/imgrush.com) for a month - presumably it's been down for that long).

### CODE REVIEW

**Comment by andytuba** [comment]
Merged to release-4.6.0 3e099524b9ea01993138436c4d3c3b51f17bc93e

**Comment by Ajedi32** [comment]
This should be moved to a new milestone or closed. (I guess it's merged. Does it need to be merged anywhere else?)

**Comment by andytuba** [comment]
Needs to be merged back to master eventually.

**Comment by mc10** [comment]
Merged with merge conflicts manually handled.

**Pull request merged**
