### PR TITLE
changed futurism.co to futurism.com

### PR DESCRIPTION
**Pull request by dansutera**
to reflect the new domain, thanks!  please let me know if I did anything wrong...

### CODE REVIEW

**Comment by mc10** [comment]
Do old `futurism.co` links still redirect properly? If so, I think we should also keep support for links using the old domain.

**Comment by dansutera** [comment]
Hi Kevin,

Thanks for looking at this!  We tested out the new changes and it works
both with futurism.com and with the old futurism.co links.  This is because
the old links are .jpg’s.  So yes, it supports both.

Cheers,

Dan

**Comment by mc10** [comment]
My question is just in the `detect` function, shouldn't you reference the old links as well, using `href.indexOf('futurism.co') !== -1 || href.indexOf('futurism.com') !== -1`?

**Comment by andytuba** [comment]
What @mc10 said -- leave the detect as-is, and make the hosts `[ 'futurism.com', 'futurism.co' ],

**Comment by dsutera** [comment]
Hi guys, I just made the recommended changes and committed.  Tested and all looks good for both old and new.  Thanks for the help!

**Comment by mc10** [comment]
Looks good to me!

**Pull request merged**
