### PR TITLE
Remove defunct hosts: vidlit, oddshot

### PR DESCRIPTION
**Pull request by larsjohnsen**

### CODE REVIEW

**Comment by mc10** [comment]
At a brief glance it seems like iloopit is still around?

**Comment by BenMcGarry** [comment]
> At a brief glance it seems like iloopit is still around?

Was it always what is it now? Looks like it might have changed.

**Comment by mc10** [comment]
I think the URL format is still the same, and it [looks like it's still being used (NSFW)](https://www.reddit.com/domain/iloopit.net/).

**Comment by larsjohnsen** [comment]
You're right, @mc10. Seems that Loopit is only broken on the test URL.

**Pull request merged**
