### PR TITLE
Keyboard shortcuts for adding links, superscript and quotes

### PR DESCRIPTION
**Pull request by erikdesjardins**
Resolves the last remaining part of #531.

ctrl-+ (ctrl-shift-=) for superscript
ctrl-k for links
ctrl-> (ctrl-shift-.) for quotes (there didn't seem to be a standard so I chose this on a whim, I'm open to suggestions)

### CODE REVIEW

**Comment by pmoody-** [comment]
OOC, I can't find the setting to control this behavior. ctrl-k for links is particularly bothersome for me since  I use emacs keybindings on my linux desktop/laptop, so ctrl-k is delete line (and ctrl-a is move-to-beginning-of-line, ctrl-e is move-to-end-of-line, etc)

**Comment by andytuba** [comment]
> OOC

Eh?
> emacs bindings

I've heard remarks from some veteran Mac users about the same. 

> setting to control this behavior

https://www.reddit.com/#!settings/commentTools/keyboardShortcuts

@erikdesjardins Interested in making options for the comment tool keyboard shortcuts?

**Comment by pmoody-** [comment]
OOC, out of curiosity.

> I've heard remarks from some veteran Mac users about the same.

linux tends to be bastard step child. On mac, the apple key tends to be the modifier for these sorts of keyboard shortcuts, so ctrl-k/a/e work as an emacs user would expect since apple-k is what's actually bound to insert-url. At least that's what I've observed on the other webapps that implement similar features (google docs, gmail, etc).

**Comment by erikdesjardins** [comment]
@andytuba will do.

**Comment by pmoody-** [comment]
Thanks!

**Pull request merged**
