### PR TITLE
Fix various accessibility issues

### PR DESCRIPTION
**Pull request by wojtekmaj**
As DIVs were used, the elements were not properly behaving according
to accessibility guidelines, most notably weren't accessible using
keyboard

Please check if the buttons are rendering properly, they should have, although I couldn't get my dev env set up fully, so I just applied my changes using developer tools to make sure they look okay.

### CODE REVIEW

**Comment by andytuba** [comment]
Thanks, this is a great contribution, and more accessibility is always better.

I'm a bit concerned about adding `!important` in the CSS though. It looks like you're trying to fix styling issues created by switching from `div` and `span` to more accessible `button` tags. Is there a good compromise, like adding `aria` tags or using `a` instead of `button`?

**Comment by andytuba** [comment]
Also the whitespace is a little wonky, maybe somebody else can help with the menial lint fixups right before merging.

You mentioned trouble setting up your dev environment. Did you get stuck at some particular step that we could help with?

**Comment by wojtekmaj** [comment]
You are absolutely right @andytuba and I share your concerns. It's the matter [CSS specifity](https://css-tricks.com/specifics-on-css-specificity/). I could switch these classed from `.className` to `tagName.className` to make them "stronger" than `tagName { ... }`, which probably is not a bad idea, I just need to make sure it won't break anything. Hang on then :)

**Comment by erikdesjardins** [comment]
`.className` is already more specific than `tagName` (inline styles > ids > classes > elements), so I think most of those selector changes shouldn't be necessary.

**Comment by wojtekmaj** [comment]
Ah, nice catch. I don't know why it didn't work for me at first. Fixed :)

**Comment by wojtekmaj** [comment]
Could we have a second look on this? It's likely to be affected by i18n changes a lot in the nearest future.

**Pull request closed without merging**
