### PR TITLE
gulp add-module --file newModule.js 

### PR DESCRIPTION
**Pull request by andytuba**
to add new modules to browser manifests

### CODE REVIEW

**Comment by allthefoxes** [comment]
This is confusing me.

You just want modules.js in each of the final builds or what?

**Comment by allthefoxes** [comment]
OHHHHHHHHHHH this is a tool that adds file names to the manifests?

**Comment by andytuba** [comment]
you got it

**Comment by allthefoxes** [comment]
Cool, so this would just be a tool for people to use to make life easy. 

I like

**Comment by andytuba** [comment]
100%.  and i'll copy-pasta it for templates if i ever get around to refactoring them/

**Pull request merged**
