### PR TITLE
Remove hardcoded scroll style

### PR DESCRIPTION
**Pull request by beck**
Fixes https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2628

### CODE REVIEW

**Comment by thybag** [comment]
Think the linter on travis is complaining because it wants you to use the new ES6 magic, ie. `_moveToThing(target, { scrollStyle: scrollStyle });` can be just `_moveToThing(target, { scrollStyle });`

**Comment by erikdesjardins** [comment]
:-1:  I'm still not convinced that #2628 is valid.

`mediaBrowseMode` has always locked to top and ignored the selected scroll style, by design. Maybe there was a bug in dev where it didn't, but not in any release, AFAIK. [The post](https://www.reddit.com/r/RESissues/comments/40mftf/bug_keyboard_nav_uses_lock_to_top_when_it_should/) linked in #2628 is a different issue.

[Try out a 4.5.4 build and see for yourself.](https://github.com/honestbleeps/Reddit-Enhancement-Suite/files/191030/res-4.5.4.zip)

This also ruins the UX for anyone that uses j/k to scroll, because you won't be able to see the expandos once you get the bottom of the page.

A better solution to your problem would be to (have an option to? or just default behaviour with fixHideLinks) make hidden posts transparent instead of removing them.

**Comment by beck** [comment]
> mediaBrowseMode has always locked to top and ignored the selected scroll style, by design

Is this good design?

With this change, it now uses my pref `directional` and the expandos step down the list of posts instead of the entire site jerking downward.

> you won't be able to see the expandos once you get to the bottom of the page.

Is it fair to consider this a separate bug that should be addressed?

What I see happening locally:

If the image loads quickly `directional` scrolling will consider the image height and scroll just enough to keep the expando in view.  If the image is slow to load, the scroll finishes and the image falls off the bottom.

This change definitely makes this race bug more painful—IMO best to expose it vs hide it by overriding user pref with hardcoded behavior.

I see another pull of similar concerns:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/2809

**Comment by erikdesjardins** [comment]
Fixed in a slightly different way by some other PRs, see #2628

**Pull request closed without merging**
