### PR TITLE
Add Travis task to run JSHint and JSCS over all files

### PR DESCRIPTION
**Pull request by mc10**
We can fine tune JSHint and JSCS so that they don't complain about problems that aren't, well, problems, but it's nice to get started with Travis. Works towards #1112 and #1481.

@honestbleeps I believe you have to flip Travis on for this project on their website: https://travis-ci.org/

EDIT: Added JSCS support.

### CODE REVIEW

**Comment by andytuba** [comment]
:+1:

**Comment by mc10** [comment]
We should honestly just decide to drop one or the other. I'm fine with either way but I guess that should probably be a separate issue.

**Comment by andytuba** [comment]
Let's do grunt for now since you already put in the legwork and we can maybe migrate over eventually.

**Comment by andytuba** [comment]
@honestbleeps Travis integration on this repo?  https://travis-ci.org/  looks like a pretty streamlined process if you login via github (top right)

**Pull request merged**
