### PR TITLE
updated imgur host to always load gif/gifv/mp4 over https

### LINKED ISSUE #3635: Gifv on imgur switches to http:// instead of https://
Whenever you expand an gifv on imgur, RES seems to switch to http:// instead of https://

How to reproduce:
Make sure you start with a clean cache.
Open up the console, go to a case and expand the image. You can see gifv going over http://

Test cases

http-link with .jpg, switches correctly to https://
https://www.reddit.com/r/pics/comments/5dvrmn/american_in_vietnam/

http-link with gifv, stays on http://, should be https://
https://www.reddit.com/r/woahdude/comments/5dvt5n/laser_pointer_through_thin_plastic/

https-link with gifv, switches to http://, should be https://
https://www.reddit.com/r/gifs/comments/5dsn06/octopus_wants_to_fight_a_scuba_diver/

Small note: gfycat also fails to switch to https:// from http:// but https:// stays https:// for gfycat.

- Night mode: false
- RES Version: 5.0.3
- Browser: Firefox
- Browser Version: 50
- Cookies Enabled: true
- Reddit beta: false

Also posted on /r/RESissues/, github might be easier to track this.

### PR DESCRIPTION
**Pull request by dhensche**
fixes #3635 
on another note, should the host module itself maybe always make sure the request is being made over https? or are there hosts that don't support it?

edit (@erikdesjardins): closes #3451

### CODE REVIEW

**Comment by BenMcGarry** [comment]
Ref Dupe #3451

**Comment by erikdesjardins** [comment]
Thanks!

**Comment by remram44** [comment]
Since recently, no image from imgur.com will expand on Reddit. Is this because of this?

From my location both imgur.com and i.imgur.com have invalid SSL certificates (Chrome says "security certificate is from a.ssl.fastly.net")

**Comment by BenMcGarry** [comment]
@remram44 can you link to a post where the expand doesn't work?

**Comment by remram44** [comment]
From the front page:



You can see the submitted link is HTTP, and the rewritten link doesn't load.

**Comment by BenMcGarry** [comment]
Works fine for me: http://i.imgur.com/iR49TG3.png

What other extension do you have active?

**Comment by erikdesjardins** [comment]
This change only affects .gifv links, so this can't be it. PR comments are not the right place to discuss potential issues, please post to /r/RESissues (preferred) or create a GitHub issue.

**Pull request merged**
