### PR TITLE
Update Tuckbot to use embedded webpage

### PR DESCRIPTION
**Pull request by kyleratti**
This switches Tuckbot.tv from using the inline video player to an embedded video player

Relevant issue: N/A
Tested in browser: Firefox 79.0b2

### CODE REVIEW

**Comment by kyleratti** [comment]
Merged latest changes from `master` branch to get a passing check status

**Comment by BenMcGarry** [comment]
By swapping this to iFrame Tuckbot will not longer expand automatically under "Show Images" and will require manual expansion. Are you ok with this?

**Comment by kyleratti** [comment]
@BenMcGarry are you referring to this button at the top of the subreddit page?

image

Tuckbot is strictly for hosting mirrored videos so as long as you can expand the image in-line with the comments, I think losing that functionality is OK. Unless you have another recommendation that may fit better for this use-case?

image

Thanks for checking

**Comment by BenMcGarry** [comment]
Yeah it will still expand there just not on Show images at the top. We'll merge this once we have passed through the hotfix run over the next few days as we weed out a few issues.

**Comment by kyleratti** [comment]
Yep - that's fine by me. Sounds good - thanks Ben!

**Pull request merged**
