### PR TITLE
First pipeline test

### PR DESCRIPTION
**Pull request by BenMcGarry**
GH actions pipeline.

TODO:

- [ ] Fix Coveralls
- [ ] Fix SauceLabs
- [ ] Add Deploy back in

### CODE REVIEW

**Comment by BenMcGarry** [comment]
@erikdesjardins You wouldnt happen to know saucelabs wont connect? Just returns:

> ⚠ Error connecting to ondemand.saucelabs.com on port 80.
> View results: https://saucelabs.com/tests/undefined/

**Comment by BenMcGarry** [comment]
GH actions doesnt send env vars to forked pr's. Merging to mainline after talking to bleeps on call to test the action. This will only merge testing capabilities. No deployment.

**Comment by erikdesjardins** [comment]
@BenMcGarry yeah, we'll probably just have to stop running tests on PRs (this was a problem for us at $JOB too lol, we had to have everyone push to the main repo and stop using forks, until they [added an option](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) to allow that--which is not safe on public repos so we can't use it here).

So there are a few options:
- have trusted contributors push wip branches to hb/RES instead of their forks, so at least we get test runs in that case
- use something like bors/mergify, which will push approved PRs to a staging branch in the main repo to run tests, then automatically merge them if it passes

**Comment by BenMcGarry** [comment]
@erikdesjardins After merging the tests to master saucelabs still doesnt like to connect, we added the env variable to GitHub but still throws an error.

Since Browserstacks now own nightwatch going to try move there as hopefully its got nicer intergration. I think for the rate the project is now, testing on main merge will probably be the easiest option to prevent over-engineering a solution.

**Pull request merged**
