### PR TITLE
[i18n] Add all titles to previously translated modules

### PR DESCRIPTION
**Pull request by wojtekmaj**
To be merged after #3776 as it includes its changes.

Gotta love multi cursors in my IDE

### CODE REVIEW

**Comment by erikdesjardins** [comment]
FYI I'm going to force-push to this branch to resolve conflicts and then merge as soon as the build passes

**Comment by wojtekmaj** [comment]
Aaaah I fixed that this second!

**Comment by erikdesjardins** [comment]
That works too

**Comment by erikdesjardins** [comment]
Great, thanks!

**Pull request merged**
