### PR TITLE
Port 4.6.1 changes back to master

### PR DESCRIPTION
**Pull request by erikdesjardins**
~~Actually #2603, not master, [diff](https://github.com/erikdesjardins/Reddit-Enhancement-Suite/compare/local-gulp...reconcile-4.6.1-master).~~
[master...release/4.6.1](https://github.com/honestbleeps/Reddit-Enhancement-Suite/compare/release/4.6.1)

### CODE REVIEW

**Comment by mc10** [comment]
This should probably be merged in sooner rather than later to avoid any more merge conflicts.

**Comment by andytuba** [comment]
There'll be a little more to come for 4.6.1 release, but yep, what mc10 said.

**Comment by mc10** [comment]
Hmm, so the commits are actually different on the branches. We should probably ditch the release/4.6.1 branch after that release is over and build a new 4.6.2 one based off master so history doesn't diverge too much.

**Comment by andytuba** [comment]
Yeah, @erikdesjardins skipped some and had to tweak a lot of them.  

Do you mean basing 4.6.2 on the current state of master? I'd rather keep 4.6.2 pretty slim and cherry-pick with lots of manual oversight, or just jump to 4.7.0 released from master.

**Comment by mc10** [comment]
That makes more sense. (y)

**Pull request merged**
