### PR TITLE
Update changelog file to use Markdown

### PR DESCRIPTION
**Pull request by Ajedi32**
Basically: `changelog.txt` -> `CHANGELOG.md` (And all the obvious changes that go with that.)

Pro tip: `git diff -w` might help with reviewing this change. I changed a lot of indentation.

### CODE REVIEW

**Comment by KamranMackey** [comment]
This looks great to me. :+1:

**Comment by andytuba** [comment]
You should start a new 4.7.0 section and first item "Converted changelog to markdown (thanks @Ajedi32)" :grinning:

**Comment by andytuba** [comment]
It looks great, thanks for converting it!

**Comment by allthefoxes** [comment]
I thought I already had it in markdown?
Or do you mean the github file?

**Comment by Ajedi32** [comment]
@allthefoxes Yes, this PR updates the file in the repository on GitHub (`changelog.txt`).

@andytuba Thanks, I'll add that once I get home tonight.

**Comment by Ajedi32** [comment]
How's that?

FYI I'm basing a few of the formatting choices for this changelog on the [example](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md) in https://github.com/olivierlacan/keep-a-changelog

**Comment by Ajedi32** [comment]
This is now on master: 01e436022a176bfd727da9a0f419fcbd1aa06d78

**Pull request closed without merging**
