### PR TITLE
[WIP] jscs: Use Node style guide as a preset

### PR DESCRIPTION
**Pull request by mc10**
This will take a long while to do (especially as it depends on #2299), so this won't be ready for quite some time.

### CODE REVIEW

**Comment by andytuba** [comment]
:+1: for tooling

**Comment by erikdesjardins** [comment]
Another :+1:, it's gonna be awesome when we have all PRs linted with this.

What do you think about turning off `requireCapitalizedComments` (IMO it makes short comments look worse and it's too nitpicky) and maybe not requiring braces on case/default statements? (they're verbose enough with `break;`)

That would be: `"requireCurlyBraces": ["if", "else", "for", "while", "do", "try", "catch"]`.

**Comment by andytuba** [comment]
:+1: on erik's suggestion

**Comment by mc10** [comment]
Personally I'm more of a fan of all-caps comments but it'd be more practical not to require them.

**Comment by erikdesjardins** [comment]
Also I'd be fine with [requireDollarBeforejQueryAssignment](http://jscs.info/rule/requireDollarBeforejQueryAssignment.html), if you want to enforce that.

I don't think it will catch stuff like this, though:

    var $foo = $('#foo');
    var notPrefixed = $foo.find('.bar');

**Comment by mc10** [comment]
Thanks! It's better than nothing, I'd say.

**Pull request closed without merging**
