### PR TITLE
Implement i18n in RES gear menu and some top-level interface items

### PR DESCRIPTION
**Pull request by wojtekmaj**
Relevant issue: 
Tested in browser:

### CODE REVIEW

**Comment by andytuba** [comment]
Neat! You can probably reuse some existing strings, e.g. module titles or options, instead of adding new keys to strings to translate -- and using CSS to handle the formatting eg for lowercase menu items.

**Comment by wojtekmaj** [comment]
Actually this is what I did initially and then decided not to, because gear menu is lowercase. And I couldn't use just `text-transform: lowercase` as that would also change "RES" to "res" and such.

**Comment by wojtekmaj** [comment]
Well, I could reuse *some* like night mode, but it's up to you - I thought it would be clearer to have them all in one place. Plus, we might want to name the toggle differently in the future.

**Comment by andytuba** [comment]
Good point. Now that I'm looking into the actual strings, I agree with your choice to just moving the existing text into the localized strings.

**Comment by erikdesjardins** [comment]
Looks good!

**Pull request merged**
