### PR TITLE
KeyboardNav: Accept input on anchor

### LINKED ISSUE #2976: Key navigation broken after opening comments by mouse click
Browser: Chrome 50
Master branch

After clicking (open in new tab / middle click) on the comments link `a.bylink.comments.may-blank`, `document.activeElement` will point to that anchor. `handleKeyPresses` https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/keyboardNav.js#L783 only accepts keypresses when `document.activeElement` is `body`.

### PR DESCRIPTION
**Pull request by larsjohnsen**
Does not appear to have any side-effects. 

Fixes #2976

### CODE REVIEW

**Comment by andytuba** [comment]
Sounds probably good to me except for enter, which I might see some people rebind. 

Related idea : after submitting a comment, focus is stuck in the submit button. Should we also accept keyboard input from buttons (except space or enter)? Or after submit, put focus back on body?

**Comment by larsjohnsen** [comment]
Perhaps blur (`document.activeElement.blur()`) if the keyboard input is anything other than tab, space or enter?

**Comment by larsjohnsen** [comment]
Possible solution:

`	// Allow navigation when activeElement is an anchor when input has no default behavior
	if (document.activeElement.tagName === 'A') {
		const hasDefaultBehavior = ['tab', 'shift-tab', 'enter', 'space'].includes(niceKeyCode(e.charCode));
		callbacks = getCommandsForKeyEvent(e);

		if (!hasDefaultBehavior) {
			document.activeElement.blur();
		}
	}`

**Comment by larsjohnsen** [comment]
Closing this since created a PR from wrong branch

**Pull request closed without merging**
