### PR TITLE
Various quickMessage improvements

### LINKED ISSUE #1952: quick.message.options.sendAs
Options:

* current user (default)
* mod of current subreddit
* last selected
* last selected on this page load

### LINKED ISSUE #1953: show moderator shield icon on quickmessage "From" when sending as subreddit
especially useful if #1952 is implemented

### LINKED ISSUE #2071: quickmessage body should automatically include link to current page
if launched from user info popup, then link specifically to current comment plus context

option to disable, of course

### LINKED ISSUE #2087: Thought: quickMessage handling message/compose links in-page?
Could quickmessage be expanded to handle compose links?

i.e. https://www.reddit.com/message/compose/?to=AutoModerator&subject=theydidthemath&message=update

Opening that in page, with the fields filled in?

### LINKED ISSUE #2150: quick message doesn't respect username hider
http://www.reddit.com/r/resissues/comments/312ilj/_/

quick message should ask username hider for the current user's display username (but hider should return undefined if not enabled) and fall back to displaying current username.

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2150, fixes #2087, fixes #2071, fixes #1953, fixes #1952.
image

Dropdown box is disabled if there are no choices:
image
cursor
Should the "last selected" sendAs be per-user?
Should we host the shield icon instead of referring to reddit's spritesheet?

### CODE REVIEW

**Comment by andytuba** [comment]
We should definitely host the shield icon instead of relying on reddit's spritesheet, which changes more often than we release.

**Comment by andytuba** [comment]
> Should the "last selected" sendAs be per-user?

Not sure what you're asking.. like, should the user be able to specify "when logged in as FooMod, always use Foo; but when logged in as BarMod, always use last selected"? 

if it's that, I would say "maybe -- keep an ear out for people requesting/complaining".

**Comment by andytuba** [comment]
This all looks super-duper rock and roll aside from the shield CSS / image.

**Comment by erikdesjardins** [comment]
Damn, I really need to do a better job of explaining stuff. What I mean by "last selected per-user" is for it to remember which user you selected for each account, i.e. "Last time you were logged in to /u/erikdesjardins, you selected /r/erikdesjardins to send messages from. Last time you were logged into to /u/otherAccount, you selected /r/someSubreddit...". Currently it just stores the last user/subreddit you selected, regardless of what account you were logged in to.

Although I'd guess that most people probably either mod the same subreddits or don't mod anything on their alts, so the current implementation should be fine for now.

sprite-reddit emwqffwtzwo is the shield icon, if we're gonna put it in /r/enhancement (or did you want to wait until we distribute them in RES?)

**Comment by andytuba** [comment]
Yeah, that sounds like a nice usability tweak. Looks like it's easy - just tack current username onto the "lastSentAs" resstoarge key.

We're out of image slots on /r/Enhancement :(  let's just go for broke and hope we get RES image distribution released before the icon hypothetically breaks.

**Pull request merged**
