### PR TITLE
set hoverDelay to stated default

### PR DESCRIPTION
**Pull request by aperson**
The description says the default value is 800, when it is actually set to 1000.

### CODE REVIEW

**Comment by KamranMackey** [comment]
LGTM :+1:

**Comment by mc10** [comment]
Alternatively, change the description to be 1000, as everyone using RES right now defaults to 1000.

**Comment by andytuba** [comment]
:+1: nix value from the description, default value should be surfaced from the code instead of incorrectly duplicated in description.

**Comment by aperson** [comment]
Done.

**Comment by andytuba** [comment]
Thanks!

**Pull request merged**
