### PR TITLE
Add a host module for ThreadShots.com

### PR DESCRIPTION
**Pull request by sangaline**

### CODE REVIEW

**Comment by sangaline** [comment]
It's tested and working with the site.

working

**Comment by andytuba** [comment]
Code looks good and works fine. I'd like to double-check with the threadshots folks that they're okay with this, then we're good to go.

**Comment by andytuba** [comment]
@sangaline On further review, there are a few problems with this PR:

* Scraping HTML with a regexp is fragile, so if threadshot changes their DOM then this site module will be broken for several months.
* Can't find an official API 
* Can't find a policy about hotlinking
* Threadshots contact never responded to my email from when you first submitted this PR
* [One reddit post linking to threadshots since 4 months ago](https://en.reddit.com/domain/threadshots.com?limit=50) -- is there any more activity in comments?

Can you find a better solution than scraping, and get in touch with the threadshots people to ask about embedding?

**Comment by erikdesjardins** [comment]
Closing due to concerns brought up by @andytuba and lack of usage (no posts on reddit [in the past 8 months](https://reddit.com/domain/threadshots.com/))

**Pull request closed without merging**
