### PR TITLE
Replace gear icon with Batch gear icon

### PR DESCRIPTION
**Pull request by erikdesjardins**
Although the current gear is somewhat iconic, so maybe it wouldn't be a good idea to replace it.

imageimage
imageimage

### CODE REVIEW

**Comment by andytuba** [comment]
flat definitely is the trend the days.

**Comment by gavin19** [comment]
Looks better! Maybe step it down to 15px so it doesn't make the user bar any taller.

Minor tweaks - `:` is sufficient for those pseudo-elements. We still need the webkit-prefixed variant for `user-select` but I can't see that it's needed in this instance?

**Comment by erikdesjardins** [comment]
@gavin19 Yeah, those elements aren't selectable in the first place, I have no idea what I was thinking.

I do realize that we can use `:`, since that's how it was before CSS3, but I feel `::` makes more sense semantically, since it's used for all other pseudo-elements, while `:` is for pseudo-classes. Although it's not like someone won't know what `:after` is, so I can change it if you want.

**Comment by andytuba** [comment]
sorry about all the crazy assigns. github mobile client is a bit twitchy

**Comment by andytuba** [comment]
i haven't put much thought into it, but ::pseudo-element / :pseudo-class() does feel habitual..

**Pull request merged**
