### PR TITLE
Support yarn

### PR DESCRIPTION
**Pull request by erikdesjardins**
We will continue to support developing with `npm` unless there's some big improvement that requires dropping it [read: for the foreseeable future].

https://github.com/yarnpkg/yarn

### CODE REVIEW

**Comment by Ajedi32** [comment]
👍 Cool.

Might want to tell Travis to cache the Yarn cache directory as described in [the docs](https://yarnpkg.com/en/docs/install-ci#travis-tab):

```
cache:
  directories:
  - $HOME/.yarn-cache
```

**Comment by mc10** [comment]
Is the `yarn.lock` supposed to be checked into version control?

**Comment by erikdesjardins** [comment]
Planning on it, going to wait a few builds so we have a baseline (since it made zero difference before: #3298).

**Comment by erikdesjardins** [comment]
Ah, the question everyone asks ([yes](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control)).

**Pull request merged**
