### PR TITLE
Fix "days ago" in Jan/Feb

### LINKED ISSUE #2583: Account age (days) won't work in January or February
Since it [will try to access](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/c2eac92fafca7bc532ba77477a0b97329f2801f0/lib/core/utils.js#L1559) `m[-2]` (changed in a8f29d8d297692180833ffc692becff47a9b33fe).

### PR DESCRIPTION
**Pull request by andytuba**
Closes #2583 

Adds QUnit tests to travis
Adds QUnit tests for niceDateDiff, skipping a failing test:

>> niceDateDiff: Mar 31 2014 - May 01 2015 = 1 year, 1 month and 1 day
>> Message: RESUtils.niceDateDiff(new Date("Mar 31 2014"), new Date("May 01 2015"));
>> Actual: "1 year and 1 month"
>> Expected: "1 year, 1 month and 1 day"

### CODE REVIEW

**Comment by Ajedi32** [comment]
> Adds QUnit tests to travis

Nice. I was surprised to learn that Travis was just running JSHint and didn't actually have any tests attached to it. It'd be great to start moving in the direction of full test coverage for RES if at all possible. (Though obviously given the current state of things getting full test coverage would be a huge task, it's never too late to start.)

**Comment by mc10** [comment]
@andytuba These need to be merged into master as well.

**Comment by andytuba** [comment]
@mc10 Yeah, may as well sooner than later.

**Comment by andytuba** [comment]
@Ajedi32 It'll be great to build up test coverage. Got any opinions for what to start with for testing? https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2587

**Comment by Ajedi32** [comment]
@andytuba I have no idea. My usual approach in situations like this is to just add tests whenever you create a new feature or fix a bug. (Test driven development.) Not sure what the best approach is for making a concerted effort to add tests after the fact.

**Comment by andytuba** [comment]
The approach we're trying at work is writing tests first for high-use features which, if broken, would get a hotfix pushed in a few weeks. To identify those parts of RES, I plan on consulting the known issues, then skimming over the modules options.

**Comment by Ajedi32** [comment]
Yeah, it's probably a good idea to go for the high-value low hanging fruit first.

**Pull request merged**
