### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### honestbleeps/Reddit-Enhancement-Suite now has a Chat Room on Gitter

@mc10 has just created a chat room. You can visit it here: [https://gitter.im/honestbleeps/Reddit-Enhancement-Suite](https://gitter.im/honestbleeps/Reddit-Enhancement-Suite?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/honestbleeps/Reddit-Enhancement-Suite?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by andytuba** [comment]
@mc10 How about irc://irc.snoonet.org/enhancement?

**Comment by mc10** [comment]
@andytuba Didn't realize this got sent automatically... I was just playing around with Gitter.

**Comment by andytuba** [comment]
Sounds like a nice turnkey solution :p

**Comment by erikdesjardins** [comment]
Closing for cleanup, can reopen if we decide to use Gitter

**Pull request closed without merging**
