### PR TITLE
highlight nsfw buttons

### PR DESCRIPTION
**Pull request by andytuba**
and an option to turn it off, of course

closes #1804 

screen shot 2015-03-29 at 3 52 13 pm

screen shot 2015-03-29 at 3 52 05 pm

### CODE REVIEW

**Comment by agentlame** [comment]
Not to knock anyone's work, but I'm not sure those stand out enough to have the desired effect.  Still, glad it made it in!

**Comment by allthefoxes** [comment]
@agentlame I agree. I would not notice that on my screen.

Is there any issues with making the stripes red or something?

**Comment by mc10** [comment]
Maybe make red versions of the expando buttons? The stripes are pretty subtle.

**Comment by andytuba** [comment]
They're at ~15% opacity, we could easily bump that up to make it more obvious.

**Pull request merged**
