### PR TITLE
Improve night mode

### PR DESCRIPTION
**Pull request by mc10**
Hopefully addresses problems in #2279 at some point, but until I figure out the problem I'll keep fixing some minor issues.

### CODE REVIEW

**Comment by andytuba** [comment]
Thanks for clean-up!  While you're in there, there's a report of some weirdness with nightmode setting the localStorage key on not-www.reddit.com (and not getting cleared out when turning off NM?)

**Comment by mc10** [comment]
Hmm maybe that's the problem... perhaps localStorage is getting trashed across subdomains? I'm assuming we still use localStorage for our own RESStorage.
* http://stackoverflow.com/questions/4026479/use-localstorage-across-subdomains
* http://stackoverflow.com/questions/4177803/can-html5-databases-and-localstorage-be-shared-across-subdomains

**Comment by andytuba** [comment]
As I understand it, RES storage comes from a local storage

**Comment by andytuba** [comment]
Nevermind that comment, will sort it out tomorrow from desktop

**Comment by andytuba** [comment]
localStorage is siloed by subdomain. Since reddit.com redirects to www.reddit.com (for their SSL cert, I believe), we can't take advantage of localStorage in reddit.com (no subdomain).  




Yeah, Chrome RES' RESStorage is populated from the extension's localStorage in chrome-extension://kbmf...: 
screen shot 2015-06-14 at 12 35 56 pm

**Comment by andytuba** [comment]
I think the "nightmode stuck on subdomains" could be resolved by turning off nightmode and removing the tab's localStorage as soon as RESStorage loads to affirm "no night mode isn't active right now after all".. probably a little flicker of nightmode styling which might confuse the user or other modules which pull values from CSSS ... but hopefully modules.nightMode can win the race

**Comment by mc10** [comment]
I can't figure out the ANM issues, but I'll merge this in anyways as a minor improvement.

**Pull request merged**
