### PR TITLE
Adding QwipIt host

### PR DESCRIPTION
**Pull request by grafixoner**
This adds ability to load in http://qwip.it assets. 

Can be tested using the following URL.
https://www.reddit.com/r/qwips/

### CODE REVIEW

**Comment by grafixoner** [comment]
@andytuba Hey not pushing here but am wondering about how long does it take to add a host into a release?  Only reason I'm asking is so I can set some expectations for people as this is an important component to our product right now. 

Thanks
Mike

**Comment by andytuba** [comment]
@grafixoner Sorry for the delay. I had opted for a feature freeze on 4.6.0 a while ago to ease releasing. Now that 4.6.0 has been released, I'm churning through bugfixes for 4.6.1. I'm also hoping to merge all the open media hosts into 4.6.1. Not exactly sure when 4.6.1 release will, but hoping for "really soon".  

After this PR gets merged, keep an eye on r/RESAnnouncements.

---

Have you tried also reaching out to embed.ly, reddit's expando provider?

**Comment by andytuba** [comment]
Have you tried also reaching out to embed.ly, reddit's expando provider?  They could provide much better reach than RES, but I don't know about their requirements or processes for adding new hosts.

**Comment by grafixoner** [comment]
Thanks for the update, I'll keep an eye on that.  

We are currently working with embed.ly for them to work with our videos.  Once that happens I'm hopeful that they will just display. 

Thanks again.
Mike

**Comment by andytuba** [comment]
If there's a publicizable process for getting added to embedly (points of contact; requirements for oEmbed endpoint or CORS support; hotlinking policies, etc.) it would be wonderful if you could share for the benefit of other media hosts.

**Comment by grafixoner** [comment]
Sure thing, here is where you become an embed.ly provider.  http://embed.ly/providers/new 

If you have video players you have to make sure first everything works with player.js which also taps you into other providers as well. http://playerjs.io/

**Comment by andytuba** [comment]
Thanks for the pointer to that page!

**Comment by grafixoner** [comment]
Hey Andy, we got our embed.ly working so expando is on the main post.  Would be awesome to get the RES suite in place so they work in comments. :)  Let me know if there is anything you need from my end.  Thanks!!

**Comment by grafixoner** [comment]
@andytuba Hey, just checking in again it's been a while since I've reached out. 

Thanks
Mike

**Comment by andytuba** [comment]
@grafixoner Merged into release/4.6.1 and awaiting release (should be pretty soon, like "less than a month")

**Comment by andytuba** [comment]
Merged to release/4.6.1

I'll comment again on this PR when it's released.

**Comment by andytuba** [comment]
v4.6.1 rolling out now!

**Pull request closed without merging**
