### PR TITLE
README: Add Code Climate badge

### PR DESCRIPTION
**Pull request by mc10**
Code Climate gives an informative display of the complexity and duplication in our code so we can identify problem areas easier.

### CODE REVIEW

**Comment by andytuba** [comment]
I'm generally in favor of status summary images, but I'm not sure how to read "better" or "worse".  Is it basically just running JSHinting?

**Comment by honestbleeps** [comment]
that looks like an interesting tool but it doesn't seem to be free to use.

**Comment by honestbleeps** [comment]
aaaand I should've read a little further down. sorry :-)

**Comment by andytuba** [comment]
> free to use

> 100% free for Open Source, forever. Get another set of eyes on your code

**Comment by andytuba** [comment]
oh, i figured out how to dig down into the ratings reports.  

lol https://codeclimate.com/github/honestbleeps/Reddit-Enhancement-Suite/Opera/browsersupport-opera.js

**Comment by honestbleeps** [comment]
funny, though a fair number of those are bogus no? it's an interesting tool though. worth poking at a bit more.

**Comment by andytuba** [comment]
the browsersupport files probably aren't the best for testing this tool..

**Pull request merged**
