### PR TITLE
Nightmode fixes, improvements, additions

### PR DESCRIPTION
**Pull request by githue**
Notable changes include fixing some over-specific selectors (https://github.com/stevenhoward/Reddit-Enhancement-Suite/commit/afc71ddfa61f3399cc0bc08d1bd57c6719f74005#commitcomment-14802877), improving the brightness of links, and a slight change to the appearance of buttons (1px outset border).

This gif shows difference between the old and new link colors:
nightmode-pretty-02-compare

There's a whole bunch of other updates which aren't very noteworthy, too.

### CODE REVIEW

**Comment by mc10** [comment]
This needs to be updated to support the new `.scss` files.

**Comment by andytuba** [comment]
Will merge this PR as-is into release-4.6.0 and githue will open a new PR for master.  then we'll have to be conscientious about nightmode fixes going into both hotfix/4.6.X branches and PRs for master.

**Comment by mc10** [comment]
Did this PR ever get merged into release-4.6.0?

**Comment by andytuba** [comment]
Thanks for bump, merged in e3a1161482c1202f69a03d4e334f3c02b2c77899

**Pull request closed without merging**
