### PR TITLE
Make defaultContext setting apply to profile pages.

### PR DESCRIPTION
**Pull request by thybag**
See: https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/1903

### CODE REVIEW

**Comment by andytuba** [comment]
Ooh, how about `isPageType('onetype', 'anothertype')`?  Did that ever make it into master?

**Comment by mc10** [comment]
[Yep!](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/core/utils.js#L236)

**Comment by thybag** [comment]
Ah, cool hadn't seen that. Updated :)

**Comment by andytuba** [comment]
thanks! handy dandy

**Pull request merged**
