### PR TITLE
Liquipedia.net: Adding futureproof and some css changes

### PR DESCRIPTION
**Pull request by iMarbot**
Adding future-proof removal of elements using custom class. Added some recently added css for items which are commonly included in the included content. Follow up to #5176

### CODE REVIEW

**Comment by BenMcGarry** [comment]
If the browser pre-loads URLs yes.

**Comment by larsjohnsen** [comment]
The `handleLink` function is executed when the viewport is close to the expando. This causes the liquipeida html to load regardless of whether the users actually opens the expando.

**Comment by larsjohnsen** [comment]
The processing is managed in `utils/watchers.js`.  There's no easy way to override this behavior, though the current system certainly could be optimized to avoid unnecessarily preloading.

**Comment by BenMcGarry** [comment]
@larsjohnsen Is it possible to disable hosts out the box for opt-in? Not sure if we have that functionality.

@iMarbot If we can disable as standard would you want it to stay or still remove? Ill add a PR now to remove pending lars.

**Comment by honestbleeps** [comment]
Hi all, I've not chimed in in quite some time due to being busy but if I'm
understanding this behavior accurately I'd like to change it for sure.

We should have the extension be respectful of external hosts and not
preload excessively. I can put in a pr if ben can't get to it.

I feel like we shouldn't preload any non reddit stuff at all, let alone
before it's in the viewport.

**Comment by BenMcGarry** [comment]
For the next release we could set a migration to disable the module to allow it opt-in?

**Comment by BenMcGarry** [comment]
Ok, I shall remove it now and add the option of preventing excessive API requests to the todo list.

**Comment by notr1ch** [comment]
I'm the above mentioned server admin for Liquipedia. I've had to temporarily block the RES requests by responding with a 403 to the CORS preflight requests as there's currently a thread on the top of /r/leagueoflegends that is causing very high load. 

The core problem is already mentioned above - RES shouldn't be requesting the API data until the user clicks the expando. Some tournament pages on Reddit have Liquipedia links to every team / series which is playing, this can cause RES to send 50+ API requests per page load and the user ends up temporarily blocked from Liquipedia due to our rate limiting setup. The likelihood of a user interacting with more than one Liquipedia expando is quite low, even more so if they're refreshing Reddit only to see new comments (Liquipedia links are often used for live events and sometimes hidden behind spoiler blocks).

Feel free to ping me if you'd like any feedback on any new Liquipedia expando implementation in the future!

**Comment by BenMcGarry** [comment]
We are looking at pushing out a hotfix to remove your module to lower load on your servers. Apologies for this.

**Comment by notr1ch** [comment]
The requests are easily identified and dropped on our frontend servers so we're not seeing any further issues. Take your time - don't feel pressured to rush out a hotfix on our behalf.

**Comment by BenMcGarry** [comment]
We've just pushed v5.18.13 with the module removed. Should be live on all platforms within 24hours.

**Pull request merged**
