### PR TITLE
Big Nightmode Update

### PR DESCRIPTION
**Pull request by githue**
* Makes nightmode compatible with different modules and reddit features
 * e.g. Visited link color, sticky color, username colors with username highlighter disabled.
* Removes duplicate and unnecessary styles
 * The color of the NSFW tag was set in two places, yet it doesn't need to be included at all
 * Alternating background colors on link listings isn't something reddit or RES does by default, why should nightmode introduce it? Should be an option in styletweaks that works with and without nightmode.
* Removes overreaching styles
 * e.g. selectedEntry should only add BG color on .md-container, not every .md inside the container.
* Groups more selectors to reduce number of lines
* Adds new styles that were missing. e.g. white drop shadows, black text on black, etc
* Doesn't break existing nightmode themes like /r/space, /r/askreddit and /r/askscience. However /r/videos looks quite different, but that's because their stylesheet is actually having an effect. :/

Give it a twirl and see what you think.

### CODE REVIEW

**Comment by andytuba** [comment]
I'm inclined to go for broke and merge this, then use /r/resupdates to hotpatch any major bugs reported.

**Comment by githue** [comment]
/r/resupdates?

**Comment by andytuba** [comment]
Check out the new Stylesheet module's options -- RES loads its subreddit stylesheet everywhere by default.

**Comment by andytuba** [comment]
@andytuba TODO changelog

**Pull request merged**
