### PR TITLE
Remove autocomplete for command line

### PR DESCRIPTION
**Pull request by gmcclure382**
Removes auto complete suggestions from commandline dialog box. As
selecting autocomplete suggestions don't work in the first place
and even if it did, kind of takes away from the user experience.

### CODE REVIEW

**Comment by andytuba** [comment]
just gonna ignore those two stray commits..

**Comment by andytuba** [comment]
thanks!

**Comment by gmcclure382** [comment]
Thanks! Sorry about those two stray commits. I didn't realize pull requests automatically get updated with subsequent commits.

**Comment by mc10** [comment]
That's usually why you use a separate branch for each PR, so you can keep your master branch clean while you mess around as much as you wish in your branches.

**Comment by gmcclure382** [comment]
@mc10 Thank you very much for the tip, I will employ that practice immediately.

**Comment by andytuba** [comment]
Plus you can do follow-up commits on that branch in response to feedback on
the pull request, and the PR gets updated with those commits.

**Comment by gmcclure382** [comment]
Oh that makes a lot of sense, I like that idea of isolating each work item to a branch. Thank you, the both of you, for all your help. We use TFS at work (though the usage is more like SourceSafe), so git is pretty new to me.

**Pull request merged**
