### PR TITLE
Notify if subscribed post is edited

### PR DESCRIPTION
**Pull request by preethamrn**
Requested in Issue #3622 
If a user has subscribed to new comment notifications on a post, and the post has been edited since the last visit to that page, then a notification should show. This is optional and off by default.

NOTE: I've already pull requested this (#3764) but due to some issues with my organization, I'm doing it again.

### CODE REVIEW

**Comment by andytuba** [comment]
> NOTE: I've already pull requested this (#3764) but due to some issues with my organization, I'm doing it again.

:+1: on submitting from a named branch instead of master.

**Comment by andytuba** [comment]
Re: [getting a Thing object in the newCommentCount function](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/3791)

You can call `const post = new Thing(document.querySelector('#siteTable .thing')` to get a `Thing` for the original post inside of [`updateCommentCount`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/66ced58cf2e22ebb980758584b1483bce0474fdc/lib/modules/newCommentCount.js#L390).  While you're in there, could you also change [`thisCount`](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/66ced58cf2e22ebb980758584b1483bce0474fdc/lib/modules/newCommentCount.js#L383) to use `post.getCommentsLink()`?

**Comment by preethamrn** [comment]
Any reason you want to get `post.getCommentsLink()` instead of `post.getCommentCount()`? It seems like the latter would be easier since we're using `thisCount` to get the `currentCommentCount` anyway.

**Comment by andytuba** [comment]
`.getCommentCount` sounds great, I just overlooked it.

**Comment by erikdesjardins** [comment]
Sorry about the delay; thanks!

**Pull request merged**
