### PR TITLE
swirl.xyz expando support

### PR DESCRIPTION
**Pull request by klpl**

### CODE REVIEW

**Comment by zjaved** [comment]
hey andy. could you tell me what the Conern-MediaHost label means and what I should do to fix it? We really want to have this pulled. Thanks!

**Comment by andytuba** [comment]
@zjaved "Concern" in this case means "What does this PR concern / pertain to", not "I am concerned about such-and-such".  It's simply a grouper for "what sort of PR is this: feature request, bug, unconfirmed bug, etc."  I suppose I could change it from "Concern-" to "Type-" or something.

At first glance, the code looks okay. As soon as a regular RES contributor tests it, it can get merged.  (might not be immediately..)

**Comment by andytuba** [comment]
Also, I'd like to double-check with the swirl.xyz owner to OK hotlinking their content.  Do you have contact info for the site owner?

**Comment by erikdesjardins** [comment]
Released in 4.6.1

**Pull request closed without merging**
