### PR TITLE
5131 - Fix logoLink doesn't redirect to /hot/

### LINKED ISSUE #5131: logo link /hot is broken
- My browser: Firefox 68 on Windows 10
- My RES version: 5.16.10
- Am I in reddit beta (yes/no): yes
- Nodemode: yes

*What's the problem?*
Selecting /hot in logo link doesn't takes you to home page

Steps to reproduce:
Go to res console > browsing > Logo link > /hot
click on logo, it will take you to default home page which is sorted by best

What will fix it:
change add / at end so it takes you to https://www.reddit.com/hot/ instead of https://www.reddit.com/hot (which redirects to https://www.reddit.com/)

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
Not that i'm aware of

*What other browser extensions are installed?*
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Bing	1.0	true	bing@search.mozilla.org
Check4Change	2.2.3	true	check4change-owner@mozdev.org
CSGOFloat Market Checker	2.2.0	true	{194d0dc6-7ada-41c6-88b8-95d7636fe43c}
DuckDuckGo	1.0	true	ddg@search.mozilla.org
Enhanced Steam	10.0	true	jid1-YdiFiTEkQgInxA@jetpack
ETP Search Volume Study	1.2	true	etp-search-volume-study@shield.mozilla.org
Google	1.0	true	google@search.mozilla.org
IDM Integration Module	6.33.2	true	mozilla_cc3@internetdownloadmanager.com
Link Gopher	2.0	true	linkgopher@oooninja.com
Livemarks	1.21	true	{c5867acc-54c9-4074-9574-04d8818d53e8}
Purchase alternatives in Steam Store	1.1	true	{0cb9bd69-a862-4ef9-9448-6db8a424216c}
Reddit Enhancement Suite	5.16.10	true	jid1-xUfzOsOFlzSOXg@jetpack
Tree Style Tab	3.1.2	true	treestyletab@piro.sakura.ne.jp
Twitter	1.0	true	twitter@search.mozilla.org
uBlock Origin	1.20.0	true	uBlock0@raymondhill.net
Web Developer	2.0.1	true	{c45c406e-ab73-11d8-be73-000a95be3b12}
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org

### PR DESCRIPTION
**Pull request by fedemp**
Closes #5131

Relevant issue: If the logo points to `https://www.reddit.com/hot`, it's redirect to 'https://www.reddit.com/`
Tested in browser: Firefox 74

I also modified the locales to match the change.

### CODE REVIEW

**Comment by BenMcGarry** [comment]
Hey, thanks for the PR! Can you remove all changes to locale files as those are auto generated based on the single en.json file. Thanks!

**Comment by BenMcGarry** [comment]
After testing this on stable, with logoLink set to /hot it automatically redirects to /hot/ on URL. What are you seeing on FF?

**Comment by fedemp** [comment]
On FF, `reddit.com/hot` redirects to `reddit.com/` (using new design).

**Comment by BenMcGarry** [comment]
Tested on Edge Version 80.0.361.69 (Official build) (64-bit). Impacts new more so than old however no impact across both as works as intended. Thanks!

**Pull request merged**
