### PR TITLE
4.7.6 changelog

### PR DESCRIPTION
**Pull request by erikdesjardins**

### CODE REVIEW

**Comment by andytuba** [comment]
This rate of beta releases is astounding. I'm glad that RES is finally in a state where it's trivial to push out a few bugfixes.

**Comment by Ajedi32** [comment]
Shouldn't this be marked as a pre-release like all the other beta releases on the releases page? https://github.com/honestbleeps/Reddit-Enhancement-Suite/releases

**Comment by erikdesjardins** [comment]
Done. FYI the next stable release will be 5.0.0 or something with an even minor version

**Pull request merged**
