### PR TITLE
Code formatting night mode friendly

### PR DESCRIPTION
**Pull request by Scellow**
It makes the code formatting way easier to read in night mode

BG: DarkGray
Font: White

### CODE REVIEW

**Comment by allthefoxes** [comment]
Pretty sure this has already been fixed. Just waiting on a release. Thanks though.

**Comment by mc10** [comment]
This has already been fixed at around [L660](https://github.com/Scellow/Reddit-Enhancement-Suite/blob/46f224a6d618e936c117b732d8b353a4d8ec46d6/lib/modules/nightmode.css#L660).

**Comment by Scellow** [comment]
haha my CTRL + F failed :(

When this will be released ?

**Comment by andytuba** [comment]
It'll be released when it's released. We still have some big todo items to knock out.

**Pull request closed without merging**
