### PR TITLE
I18n: backupAndRestore, betteReddit, filteReddit, troubleshooter

### PR DESCRIPTION
**Pull request by wojtekmaj**
Relevant issue: #3755
Tested in browser: Chrome

Added some new i18n :)

By the way, I had to test it somehow, so I've translated all new keys to Polish in the process. No better way to translate than in context, so if you want to add it right away, there you go:

```json
	"backupAndRestoreProvidersFile": {
		"message": "Plik"
	},
	"backupAndRestoreFoundBackup": {
		"message": "Znaleziono nową automatyczną kopię zapasową na $1."
	},
	"backupAndRestoreBackupOverwriteWarning": {
		"message": "Odzyskanie kopii zapasowej permanentnie nadpisze twoje aktualne ustawienia. Czy na pewno chcesz kontynuować?"
	},
	"backupAndRestoreAfterCancel": {
		"message": "Jeśli klikniesz Anuluj, przeniesiemy Cię do strony ustawień, na której możesz wyłączyć automatyczną kopię zapasową lub stworzyć nową kopię zapasową, by nadpisać tę."
	},
	"backupAndRestoreBackupDate": {
		"message": "Data kopii zapasowej: $1"
	},
	"backupAndRestoreBackupSize": {
		"message": "Rozmiar kopii zapasowej: $1"
	},
	"betteRedditHideLinkLabel": {
		"message": "schowaj"
	},
	"betteRedditUnhideLinkLabel": {
		"message": "pokaż ponownie"
	},
	"betteRedditHideSubmissionError": {
		"message": "Wystąpił błąd podczas chowania posta. Spróbuj kliknąć ponownie."
	},
	"betteRedditUnhideSubmissionError": {
		"message": "Wystąpił błąd podczas ponownego pokazywania posta. Spróbuj kliknąć ponownie."
	},
	"betteRedditVideoYouTubeTitle": {
		"message": "Tytuł na YouTube: $1"
	},
	"betteRedditVideoViewed": {
		"message": "[Wyświetleń: $1]"
	},
	"nsfwSwitchToggleText": {
		"message": "filtr +18"
	},
	"nsfwSwitchToggleTitle": {
		"message": "Przełącz filtr +18"
	},
	"filteRedditAllowNSFWWhere": {
		"message": "gdzie"
	},
	"filteRedditAllowNSFWWhenBrowsingSubreddit": {
		"message": "Podczas przeglądania subreddita/multi-subreddita"
	},
	"filteRedditKeyword": {
		"message": "słowo kluczowe"
	},
	"filteRedditApplyTo": {
		"message": "aplikuj"
	},
	"filteRedditEverywhere": {
		"message": "Wszędzie"
	},
	"filteRedditEverywhereBut": {
		"message": "Wszędzie oprócz"
	},
	"filteRedditOnlyOn": {
		"message": "Tylko na:"
	},
	"filteRedditFilterSubredditsEverywhereButSubreddit": {
		"message": "Wszędzie oprócz subredditów"
	},
	"filteRedditFilterSubredditsAllPopularAndDomain": {
		"message": "/r/all, /r/popular i na stronach domeny"
	},
	"filteRedditSubreddits": {
		"message": "subreddity"
	},
	"filteRedditAddFilter": {
		"message": "+dodaj filtr"
	},
	"filteRedditAddSubreddits": {
		"message": "+dodaj subreddity"
	},
	"filteRedditAddCustomFilter": {
		"message": "+dodaj własny filtr"
	},
	"filteRedditCustomFiltersGroupOfConditions": {
		"message": "Grupa warunków"
	},
	"filteRedditSubredditsSubreddits": {
		"message": "subreddity"
	},
	"filteRedditForceSyncFiltersLabel": {
		"message": "synchronizuj"
	},
	"backupAndRestoreAutomaticBackupsNone": {
		"message": "Żaden"
	},
	"troubleshooterClearLabel": {
		"message": "Wyczyść"
	},
	"troubleshooterResetLabel": {
		"message": "Resetuj"
	},
	"troubleshooterEnableLabel": {
		"message": "Włącz"
	},
	"troubleshooterDisableLabel": {
		"message": "Wyłącz"
	},
	"troubleshooterBreakpointLabel": {
		"message": "Wstrzymaj JavaScript"
	},
	"troubleshooterTestNotificationsLabel": {
		"message": "Testuj powiadomienia"
	},
	"troubleshooterTestEnvironmentLabel": {
		"message": "Testuj środowisko"
	},
```

### CODE REVIEW

**Comment by erikdesjardins** [comment]
Thanks!

Unfortunately we can't import them directly as they'll get overwritten the next time we sync from Transifex.

**Comment by wojtekmaj** [comment]
Alright. So let me know when the new strings are in Transifex then and I'll apply the translations :)

**Comment by wojtekmaj** [comment]
Would you please assist me with the remaining Flow error? I honestly have no clue how to fix that. :/

**Comment by erikdesjardins** [comment]
Flow doesn't (and can't really) know the shape of the storage blob, so we have to use an `any` cast (which I've added).

**Comment by erikdesjardins** [comment]
Strings should be in Transifex less than 24 hours from now

**Comment by wojtekmaj** [comment]
Thank you!

**Pull request merged**
