### PR TITLE
Images to batch icons

### PR DESCRIPTION
**Pull request by andytuba**
Swapped out a few icon images for batch font icons.  This should supersede some of the "move icons from `url(https://aws...)` to `uri(data:...)`" PR

thanks to @erikdesjardins for suggestions.

Still need to do gear dropdown search button

### CODE REVIEW

**Comment by andytuba** [comment]
@erikdesjardins which other ones did you identify?

**Comment by erikdesjardins** [comment]
There's also the [dashboard edit button](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/core/res.css#L182), which maybe could be replaced by F139 or similar.

Other than the search magnifying glass, I think that's it, unless there's anything in [the spritesheet](https://s3.amazonaws.com/b.thumbs.redditmedia.com/tBwwK20XXxtpgudWx1L7bDXla-iotv-JA0jgA0Y-FVs.png) that could be replaced.

**Comment by andytuba** [comment]
Hmm, that spritesheet.. 

+, < and > could definitely be replaced.  I wonder if + is even used anywhere.

Should we swap out the <=  =>  and loop arrows from the image expando gallery controls? dunno which subreddits have styled those.

Comment navigator up/down buttons maybe?

NER play/pause button could definitely become a batch icon, with a smidgen of work.

**Comment by andytuba** [comment]
/r/dashboard's "refresh" button could also become a batch icon.

**Pull request merged**
