### PR TITLE
Upgrade ava to 1.4.1 and Babel to 7.4.3

### PR DESCRIPTION
**Pull request by kevinji**
I can't seem to fix the new test failures though, so any suggestions are welcome.

### CODE REVIEW

**Comment by kevinji** [comment]
I'm now thoroughly confused; I have no idea what adding a `console.error` changed but it seems to fix the issue. Maybe something (Babel?) is incorrectly assuming that the variable isn't used inside `createPair` and isn't keeping it in the function's closure?

**Comment by larsjohnsen** [comment]
Yeah, it looks like there was a bug in Babel. Updating it also resolves the issue.

**Comment by larsjohnsen** [comment]
With `console.error` 
```
function createPair() {
  // Simulates foreground listener
  const _createMessageHandler = (0, _messaging.createMessageHandler)((info, context) => new Promise(resolve => _handleMessageA(info, resolve, context))),
        a = _objectWithoutPropertiesLoose(_createMessageHandler, ["_handleMessage"]); // Simulates background listener


  const _createMessageHandler2 = (0, _messaging.createMessageHandler)((info, context) => new Promise(resolve => _handleMessageB(info, resolve, context)), true),
        {
    _handleMessage: _handleMessageA
  } = _createMessageHandler2,
        b = _objectWithoutPropertiesLoose(_createMessageHandler2, ["_handleMessage"]); // I have no idea what this changes, but this no-op fixes the test failures.


  console.error(_handleMessageA);
  return {
    a,
    b
  };
```
Without:
```
function createPair() {
  // Simulates foreground listener
  const _createMessageHandler = (0, _messaging.createMessageHandler)((info, context) => new Promise(resolve => _handleMessageA(info, resolve, context))),                                                                                                                                     
        a = _objectWithoutPropertiesLoose(_createMessageHandler, ["_handleMessage"]); // Simulates background listener


  const _createMessageHandler2 = (0, _messaging.createMessageHandler)((info, context) => new Promise(resolve => _handleMessageB(info, resolve, context)), true),                                                                                                                              
        b = _objectWithoutPropertiesLoose(_createMessageHandler2, ["_handleMessage"]);

  return {
    a,
    b
  };
}
```

**Comment by kevinji** [comment]
Sounds good, I suspect it was fixed by babel/babel#9492.

**Pull request merged**
